name = "api"
main = "src/discord/server.ts"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]
logpush = true

[[kv_namespaces]]
binding = "KV"
id = "b1f26e7bf10143c8b5e170e15db6505a"

[[d1_databases]]
binding = "DB"
database_name = "discord-db"
database_id = "c6506d9f-aa59-4ca7-9ada-cfd02ffc2d39"

[vars]