name = "api"
main = "src/discord/server.ts"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]
logpush = true

[[kv_namespaces]]
binding = "KV"
id = "8fe1c0a7c4f94a97b07b4fd81aad6f68"

[[d1_databases]]
binding = "DB"
database_name = "discord-db"
database_id = "c6506d9f-aa59-4ca7-9ada-cfd02ffc2d39"

[vars]





